inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux_rails.gemspec'
    - 'lib/logux/test/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/logux_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/logux_controller.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/logux/tasks/*.rb'
    - 'spec/requests/*.rb'

RSpec/ExpectChange:
  EnforcedStyle: block
